version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: "train_station"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5447:5432"